name: rustsec

on:
  pull_request:
    paths:
      - ".github/workflows/rustsec.yml"
      - "cargo-lock/**"
      - "cvss/**"
      - "platforms/**"
      - "rustsec/**"
      - "Cargo.*"
  push:
    branches: main

defaults:
  run:
    working-directory: rustsec

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.60.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal
      - run: cargo check
      - run: cargo test --no-default-features --release
      - run: cargo test --release
      - run: cargo test --all-features --release

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - run: cargo doc --all-features
